#----------------------------------------------------------
# GitHub-Action Part1 - Basics
#
# Copyleft (c) Eugene Pokosenko
#----------------------------------------------------------

name: My-GITHUB-Actions-Basic
env:
  APPLICATION_NAME : "MyFlask"
  PACKAGE_NAME     : "flask-deploy-ver-$ {{ github.sha }}"
  
    
  


on:
  push:
    branches: 
      - main

jobs: 
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message 
      run: echo "Hello World from My_testing job"
      

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps: 
    - name: Print Hello Message
      run: echo "Hello World from My_deploy job"
    
    


  
  
  


    
  
    
  
      
   


